server:
  port: 18115

spring:
  application:
    name: psm-incident-service
  datasource:
    url: ${PSM_INCIDENT_SERVICE_DB_URL:jdbc:mysql://localhost:3306/psm_incident?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${PSM_INCIDENT_SERVICE_DB_USERNAME:psm}
    password: ${PSM_INCIDENT_SERVICE_DB_PASSWORD:psm}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
