server:
  port: 18084

spring:
  application:
    name: psm-config-rule-service
  datasource:
    url: ${PSM_CONFIG_RULE_DB_URL:jdbc:mysql://localhost:3306/psm_config_rule?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${PSM_CONFIG_RULE_DB_USERNAME:psm}
    password: ${PSM_CONFIG_RULE_DB_PASSWORD:psm}
    driver-class-name: com.mysql.cj.jdbc.Driver
