server:
  port: 18094

spring:
  application:
    name: psm-audit-service
  datasource:
    url: ${PSM_AUDIT_DB_URL:jdbc:mysql://localhost:3306/psm_audit?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${PSM_AUDIT_DB_USERNAME:psm}
    password: ${PSM_AUDIT_DB_PASSWORD:psm}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

