server:
  port: 18112

spring:
  application:
    name: psm-moc-service
  datasource:
    url: ${PSM_MOC_SERVICE_DB_URL:jdbc:mysql://localhost:3306/psm_moc?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${PSM_MOC_SERVICE_DB_USERNAME:psm}
    password: ${PSM_MOC_SERVICE_DB_PASSWORD:psm}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

psm:
  pha-service-url: ${PSM_PHA_SERVICE_URL:http://localhost:18111}
  pssr-service-url: ${PSM_PSSR_SERVICE_URL:http://localhost:18113}
