server:
  port: 18080

spring:
  application:
    name: psm-gateway

psm:
  gateway:
    auth-service-url: ${PSM_AUTH_SERVICE_URL:http://localhost:18081}
    iam-service-url: ${PSM_IAM_SERVICE_URL:http://localhost:18082}
    master-data-service-url: ${PSM_MASTER_DATA_SERVICE_URL:http://localhost:18083}
    config-rule-service-url: ${PSM_CONFIG_RULE_SERVICE_URL:http://localhost:18084}
    audit-service-url: ${PSM_AUDIT_SERVICE_URL:http://localhost:18094}
    contractor-service-url: ${PSM_CONTRACTOR_SERVICE_URL:http://localhost:18085}
    major-hazard-service-url: ${PSM_MAJOR_HAZARD_SERVICE_URL:http://localhost:18086}
