server:
  port: 18080

spring:
  application:
    name: psm-gateway

psm:
  gateway:
    auth-service-url: ${PSM_AUTH_SERVICE_URL:http://localhost:18081}
    iam-service-url: ${PSM_IAM_SERVICE_URL:http://localhost:18082}
    master-data-service-url: ${PSM_MASTER_DATA_SERVICE_URL:http://localhost:18083}
    config-rule-service-url: ${PSM_CONFIG_RULE_SERVICE_URL:http://localhost:18084}
    audit-service-url: ${PSM_AUDIT_SERVICE_URL:http://localhost:18094}
    contractor-service-url: ${PSM_CONTRACTOR_SERVICE_URL:http://localhost:18085}
    major-hazard-service-url: ${PSM_MAJOR_HAZARD_SERVICE_URL:http://localhost:18086}
    alarm-service-url: ${PSM_ALARM_SERVICE_URL:http://localhost:18087}
    work-permit-service-url: ${PSM_WORK_PERMIT_SERVICE_URL:http://localhost:18088}
    mobile-bff-url: ${PSM_MOBILE_BFF_URL:http://localhost:18089}
    report-service-url: ${PSM_REPORT_SERVICE_URL:http://localhost:18090}
    file-service-url: ${PSM_FILE_SERVICE_URL:http://localhost:18092}
    notification-service-url: ${PSM_NOTIFICATION_SERVICE_URL:http://localhost:18093}
    inspection-service-url: ${PSM_INSPECTION_SERVICE_URL:http://localhost:18102}
    dual-prevention-service-url: ${PSM_DUAL_PREVENTION_SERVICE_URL:http://localhost:18101}
    location-service-url: ${PSM_LOCATION_SERVICE_URL:http://localhost:18103}
    video-service-url: ${PSM_VIDEO_SERVICE_URL:http://localhost:18104}
    integration-service-url: ${PSM_INTEGRATION_SERVICE_URL:http://localhost:18091}
