server:
  port: 18080

spring:
  application:
    name: psm-gateway

psm:
  gateway:
    auth-service-url: ${PSM_AUTH_SERVICE_URL:http://localhost:18081}
    master-data-service-url: ${PSM_MASTER_DATA_SERVICE_URL:http://localhost:18083}
