server:
  port: 18113

spring:
  application:
    name: psm-pssr-service
  datasource:
    url: ${PSM_PSSR_SERVICE_DB_URL:jdbc:mysql://localhost:3306/psm_pssr?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${PSM_PSSR_SERVICE_DB_USERNAME:psm}
    password: ${PSM_PSSR_SERVICE_DB_PASSWORD:psm}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
